runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v3
      id: cache-node-modules
      with:
        path: node_modules
        key: ${{ hashFiles('package-lock.json') }}
    - run: npm install
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      shell: bash
